/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 */
import type { ResponseRestfulResponse } from './responseRestfulResponse';
import type { GetApiUserSelf200AllOf } from './getApiUserSelf200AllOf';

export type GetApiUserSelf200 = ResponseRestfulResponse & GetApiUserSelf200AllOf;
