/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 */
import type { ResponseRestfulResponse } from './responseRestfulResponse';
import type { PostApiUserSignIn200AllOf } from './postApiUserSignIn200AllOf';

export type PostApiUserSignIn200 = ResponseRestfulResponse & PostApiUserSignIn200AllOf;
