/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 */
import type { ResponseRestfulResponse } from './responseRestfulResponse';
import type { PostApiUserSignUp200AllOf } from './postApiUserSignUp200AllOf';

export type PostApiUserSignUp200 = ResponseRestfulResponse & PostApiUserSignUp200AllOf;
