/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 */
import type { UserSignInReqType } from './userSignInReqType';

export interface UserSignInReq {
  captcha?: string;
  email?: string;
  password?: string;
  type: UserSignInReqType;
  username?: string;
}
