/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 */

export type UserSignInReqType = typeof UserSignInReqType[keyof typeof UserSignInReqType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSignInReqType = {
  email: 'email',
  password: 'password',
} as const;
