/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 */

export interface UserUserCreateOrUpdateInfoReq {
  avatarUrl?: string;
  birthday?: string;
  createTime?: string;
  gender?: number;
  id: number;
  mobile?: number;
  nickname: string;
  region: string;
  updateTime?: string;
  username: string;
}
