/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 */
import type { UserUserSignUpAccountReq } from './userUserSignUpAccountReq';
import type { UserUserCreateOrUpdateInfoReq } from './userUserCreateOrUpdateInfoReq';

export interface UserUserSignUpReq {
  account?: UserUserSignUpAccountReq;
  info?: UserUserCreateOrUpdateInfoReq;
  type: string;
}
