/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * bff
 * backend for frontend
 * OpenAPI spec version: 1.0.0
 */

export * from './deleteManagerMaterialDelete200';
export * from './deleteManagerMaterialDeleteBody';
export * from './deleteManagerMaterialDeleteParams';