/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityPromotionUpdateGoods } from './activityPromotionUpdateGoods';

export interface ActivityPromotionUpdateGoodsReq {
  goods: ActivityPromotionUpdateGoods[];
  id: number;
}
