/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ActivityGoodsLimitReq {
  goods_type: string;
  id: number;
  limit?: number | null;
  page?: number | null;
  sku_name?: string | null;
  spu_name?: string | null;
}
