/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface Activity {
  activity_type: string;
  cover_url: string;
  create_time?: string | null;
  end_time?: string | null;
  id: number;
  is_hot: number;
  publish_time?: string | null;
  publish_type?: string | null;
  start_time?: string | null;
  subtitle: string;
  title: string;
}
