/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ActivityGoods {
  discount?: number | null;
  id: number;
  sku_id?: number | null;
  sku_name?: string | null;
  spu_id: number;
  spu_name: string;
}
