/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ActivityBaseDetail {
  activity_type: string;
  content: string;
  cover_name: string;
  cover_url: string;
  create_time: string;
  id: number;
  subtitle: string;
  title: string;
}
