/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ActivityInfoDetail {
  discount?: number | null;
  end_time?: string | null;
  price?: number | null;
  publish_time?: string | null;
  publish_type: string;
  start_time?: string | null;
}
