/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface AdminInfo {
  age: number;
  create_time: string;
  gender: number;
  id: number;
  level: number;
  name: string;
  status: number;
  update_time: string;
  username: string;
}
