/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface AssociateRouterAuthReq {
  aid: number;
  /** 1 = associate , 0 = disassociate */
  associate: number;
  rkey: number;
}
