/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface AssociateAuthLimit {
  age: number;
  /** 1:associated  0:disassociated */
  associated: number;
  create_time: string;
  id: number;
  name: string;
  update_time: string;
  username: string;
}
