/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface AssociateRouterAuthLimitReq {
  id?: string | null;
  limit?: string | null;
  name?: string | null;
  page?: string | null;
  rkey: string;
}
