/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface CommentLimitReq {
  comment_type?: string | null;
  id?: number | null;
  limit?: number | null;
  page?: number | null;
  reply_id?: number | null;
  spu_id?: number | null;
  status: string;
  user_id?: number | null;
}
