/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { CommentLimitRes } from './commentLimitRes';

export interface CommentRes {
  data: CommentLimitRes;
  message: string;
  status: number;
}
