/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface Comment {
  comment_type: string;
  content: string;
  create_time: string;
  dislike: number;
  id: number;
  like: number;
  nickname: string;
  reply_id?: number | null;
  reply_uid?: number | null;
  spu_id: number;
  spu_name: string;
  user_id: number;
  username: string;
}
