/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface CompanyStudioDetail {
  create_time: string;
  description?: string | null;
  e_tag: string;
  established_time: string;
  founder?: string | null;
  id: number;
  logo_name: string;
  logo_url: string;
  name: string;
  region?: string | null;
  update_time: string;
}
