/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface CompanyStudio {
  create_time: string;
  established_time: string;
  id: number;
  logo_url: string;
  name: string;
  update_time: string;
}
