/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type DeleteActivityGoodsBundleParams = {
id: number;
spu_id: number;
sku_id?: number | null;
};
