/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { GameSPUDetailCompany } from './gameSPUDetailCompany';
import type { SpuTag } from './spuTag';
import type { SpuType } from './spuType';

export interface GameSPUDetail {
  company?: GameSPUDetailCompany;
  create_time: string;
  description?: string | null;
  e_tag: string;
  id: number;
  issue_time: string;
  logo_name: string;
  logo_url: string;
  name: string;
  price: number;
  tags: SpuTag[];
  types: SpuType[];
  update_time: string;
}
