/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface GameType {
  description?: string | null;
  e_tag: string;
  filename: string;
  id: number;
  logo_url: string;
  name: string;
}
