/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { GameType } from './gameType';

export interface GameTypeLimitRes {
  current: number;
  results?: GameType[] | null;
  total: number;
}
