/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface GameSPULimit {
  company_name: string;
  create_time: string;
  id: number;
  issue_time: string;
  logo_url: string;
  name: string;
  price: number;
  tag_names: string[];
  type_names: string[];
  update_time: string;
}
