/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetActivityLimitParams = {
id?: number | null;
title?: string | null;
activity_type?: string | null;
limit?: number | null;
page?: number | null;
};
