/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface GetCompanyStudioReq {
  established_end_time?: string | null;
  established_start_time?: string | null;
  founder?: string | null;
  id?: number | null;
  limit?: number | null;
  name?: string | null;
  page?: number | null;
  region?: string | null;
}
