/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetCommentLimitParams = {
limit?: number | null;
page?: number | null;
id?: number | null;
reply_id?: number | null;
user_id?: number | null;
spu_id?: number | null;
comment_type?: string | null;
status: string;
};
