/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetCompanyParams = {
id?: number | null;
name?: string | null;
region?: string | null;
founder?: string | null;
established_start_time?: string | null;
established_end_time?: string | null;
limit?: number | null;
page?: number | null;
};
