/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface GetGameLimitReq {
  end_issue_time?: string | null;
  end_price?: number | null;
  id?: number | null;
  limit?: number | null;
  name?: string | null;
  page?: number | null;
  start_issue_time?: string | null;
  start_price?: number | null;
  tag_ids?: number | null;
  type_ids?: number | null;
}
