/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetManagerAvatarAuditsParams = {
status?: number | null;
id?: number | null;
name?: string | null;
username?: string | null;
limit?: number | null;
page?: number | null;
};
