/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetManagersLimitParams = {
limit?: number | null;
page?: number | null;
id?: number | null;
username?: string | null;
name?: string | null;
gender?: number | null;
role_id?: number | null;
};
