/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetManagerRolePermissionsParams = {
role_id: number;
limit?: number | null;
page?: number | null;
name?: string | null;
path?: string | null;
method?: string | null;
};
