/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetManagerRoleRouterParams = {
role_id: number;
router_key?: number | null;
label?: string | null;
path?: string | null;
status?: number | null;
limit?: number | null;
page?: number | null;
};
