/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetRoleAuditLimitParams = {
id?: number | null;
username?: string | null;
name?: string | null;
status?: number | null;
role_id?: number | null;
limit?: number | null;
page?: number | null;
};
