/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { SpuLimitSort } from './spuLimitSort';

export type GetSpuLimitParams = {
limit?: number | null;
page?: number | null;
id?: number | null;
tag_id?: number | null;
type_id?: number | null;
name?: string | null;
start_price?: number | null;
end_price?: number | null;
start_issue_time?: string | null;
end_issue_time?: string | null;
sort?: SpuLimitSort | null;
};
