/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface GetSpuTreeReq {
  limit?: number | null;
  page?: number | null;
  spu_id?: number | null;
  spu_name?: string | null;
}
