/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type GetSkuLimitParams = {
spu_id?: string | null;
spu_name?: string | null;
id?: string | null;
name?: string | null;
limit?: number | null;
page?: number | null;
};
