/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface GetUserLimitReq {
  gender?: number | null;
  id?: string | null;
  limit?: number | null;
  nickname?: string | null;
  page?: number | null;
  username?: string | null;
}
