/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface HotActivity {
  activity_type: string;
  cover_url: string;
  create_time: string;
  discount?: number | null;
  id: number;
  price?: number | null;
  sort: number;
  title: string;
  update_time: string;
}
