/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export * from './adminInfo';
export * from './adminInfoListRes';
export * from './adminInfoRes';
export * from './associateAuthLimit';
export * from './associateAuthLimitReq';
export * from './authLimitRes';
export * from './authRes';
export * from './deletePermissionParams';
export * from './deletePermissionQuery';
export * from './deleteRouteReq';
export * from './deleteRouterParams';
export * from './disassociateParams';
export * from './getAuthLimitParams';
export * from './getPermissionAuthParams';
export * from './getPermissionParams';
export * from './loginBody';
export * from './permission';
export * from './permissionAssociateAuthLimitRes';
export * from './permissionAssociateAuthReqBody';
export * from './permissionAssociateAuthRes';
export * from './permissionDisassociateAuthReqBody';
export * from './permissionLimitQuery';
export * from './permissionLimitRes';
export * from './permissionRes';
export * from './resPonseString';
export * from './resPonseU8';
export * from './route';
export * from './routesVecRes';
export * from './updatePermissionBody';