/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ManagerInfoLimitReq {
  gender?: number | null;
  id?: number | null;
  limit?: number | null;
  name?: string | null;
  page?: number | null;
  role_id?: number | null;
  username?: string | null;
}
