/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { ManagerRolePermissionRow } from './managerRolePermissionRow';

export interface ManagerRolePermissionRowLimitRes {
  current: number;
  results?: ManagerRolePermissionRow[] | null;
  total: number;
}
