/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ManagerInfo {
  age?: number | null;
  avatar?: string | null;
  create_time: string;
  email: string;
  gender: number;
  id: number;
  mobile?: string | null;
  name: string;
  role_id: number;
  role_name: string;
  update_time: string;
  username: string;
}
