/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ManagerAvatarAuditRow {
  avatar: string;
  create_time: string;
  id: number;
  name: string;
  reason?: string | null;
  status: number;
  update_time: string;
  username: string;
}
