/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ManagerInfo {
  age?: number | null;
  avatar?: string | null;
  create_time?: string | null;
  email: string;
  gender?: number | null;
  id: number;
  mobile?: string | null;
  name?: string | null;
  role_id?: number | null;
  role_name?: string | null;
  update_time?: string | null;
  username: string;
}
