/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { ManagerInfoWithToken } from './managerInfoWithToken';

export interface ManagerInfoWithTokenData {
  data: ManagerInfoWithToken;
  message: string;
  status: number;
}
