/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ManagerRolePermissionRowReq {
  limit?: number | null;
  method?: string | null;
  name?: string | null;
  page?: number | null;
  path?: string | null;
  role_id: number;
}
