/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ManagerInfoUpdate {
  age?: number | null;
  email?: string | null;
  gender?: number | null;
  mobile?: string | null;
  name?: string | null;
  username?: string | null;
}
