/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface ManagerRolePermissionStatusReq {
  permission_ids: number[];
  role_id: number;
  status: number;
}
