/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface News {
  content: string;
  create_time: string;
  id: number;
  sort: number;
  title: string;
  update_time: string;
}
