/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type OrderBy = typeof OrderBy[keyof typeof OrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderBy = {
  DESC: 'DESC',
  ASC: 'ASC',
} as const;
