/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { PermissionAssociateAuthRes } from './permissionAssociateAuthRes';

export interface PermissionAssociateAuthLimitRes {
  data: PermissionAssociateAuthRes;
  message: string;
  status: number;
}
