/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface Permission {
  create_time: string;
  id: number;
  method?: string | null;
  name: string;
  path?: string | null;
  remark?: string | null;
  update_time: string;
}
