/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { RoleAuditRowLimitRes } from './roleAuditRowLimitRes';

export interface RoleAuditRowRes {
  data: RoleAuditRowLimitRes;
  message: string;
  status: number;
}
