/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface Route {
  create_time: string;
  key?: number | null;
  label: string;
  level: number;
  p_key?: number | null;
  path: string;
  public: number;
  sort: number;
  update_time: string;
}
