/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface Route {
  key?: string | null;
  label: string;
  level: number;
  p_key?: string | null;
  path: string;
  sort: number;
}
