/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { SendManagerEmailRes } from './sendManagerEmailRes';

export interface SendManagerEmailResData {
  data: SendManagerEmailRes;
  message: string;
  status: number;
}
