/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface Sku {
  cover_name: string;
  cover_url: string;
  create_time: string;
  description?: string | null;
  id: number;
  issue_time: string;
  name: string;
  price: number;
  spu_id: number;
  spu_name: string;
  update_time: string;
}
