/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface SkuLimitReq {
  id?: string | null;
  limit?: number | null;
  name?: string | null;
  page?: number | null;
  spu_id?: string | null;
  spu_name?: string | null;
}
