/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface SkuNotice {
  content: string;
  create_time: string;
  id: number;
  publish_time?: string | null;
  publish_type: string;
  published: boolean;
  sku_id: number;
  sku_name: string;
  title: string;
  update_time: string;
}
