/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface SkuUpdateReq {
  cover_name: string;
  cover_url: string;
  description?: string | null;
  id?: string | null;
  issue_time: string;
  name: string;
  price: string;
  spu_id: string;
  spu_name: string;
}
