/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { SpuLimit } from './spuLimit';

export interface SpuLimitRes {
  current: number;
  results?: SpuLimit[] | null;
  total: number;
}
