/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export type SpuLimitSort = typeof SpuLimitSort[keyof typeof SpuLimitSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpuLimitSort = {
  default: 'default',
  time: 'time',
  most_likely: 'most_likely',
  most_attention: 'most_attention',
} as const;
