/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface SpuNoticeLimitReq {
  id?: string | null;
  limit?: number | null;
  page?: number | null;
  publish_type?: string | null;
  published?: number | null;
  spu_id?: string | null;
  title?: string | null;
}
