/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface SpuNoticeUpdateReq {
  content?: string | null;
  id?: string | null;
  publish_time?: string | null;
  publish_type: string;
  spu_id?: string | null;
  spu_name?: string | null;
  title: string;
}
