/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface SpuUpdateRecord {
  content?: string | null;
  create_time: string;
  id: number;
  spu_id: number;
  title: string;
  update_time: string;
}
