/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface Tag {
  bg_color: string;
  border_color: string;
  create_time: string;
  description?: string | null;
  id: number;
  name: string;
  text_color: string;
  update_time: string;
}
