/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { FileObject } from './fileObject';

export interface UpdateGameTypeReq {
  description?: string | null;
  id?: number | null;
  logo: FileObject;
  name: string;
}
