/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import type { SpuFileObject } from './spuFileObject';

export interface UpdateSpuReq {
  carousel: SpuFileObject[];
  company_id?: number | null;
  cover: SpuFileObject;
  description?: string | null;
  id?: number | null;
  issue_time: string;
  name: string;
  price: number;
  tag_ids: string;
  type_ids: string;
}
