/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateCompanyStudioReq {
  description?: string | null;
  established_time: string;
  founder?: string | null;
  id?: number | null;
  logo_url: string;
  name: string;
  region?: string | null;
}
