/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateGameSpu {
  company_ids?: number | null;
  description?: string | null;
  e_tag: string;
  id?: number | null;
  issue_time: string;
  logo_name: string;
  logo_url: string;
  name: string;
  price: number;
  tag_ids: number[];
  type_ids: number[];
}
