/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateTagReq {
  bg_color: string;
  border_color: string;
  description?: string | null;
  id?: number | null;
  name: string;
  text_color: string;
}
