/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateCarouselReq {
  content?: string | null;
  cover_url: string;
  id?: number | null;
  link_url?: string | null;
  sort: number;
  subtitle?: string | null;
  title?: string | null;
}
