/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface UserDetail {
  avatar_url: string;
  banned_date?: number | null;
  banned_reason?: string | null;
  banned_start_time: string;
  birthday: string;
  create_time: string;
  email: string;
  gender: number;
  id: number;
  is_banned: number;
  mobile: string;
  nickname: string;
  region: string;
  update_time: string;
  username: string;
}
