/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface User {
  avatar_url: string;
  birthday: string;
  create_time: string;
  gender: number;
  id: number;
  is_banned: number;
  nickname: string;
  update_time: string;
  username: string;
}
