/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export * from './adminInfo';
export * from './adminInfoRes';
export * from './loginBody';
export * from './signInRes';
export * from './signUpReq';
export * from './signUpRes';