/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */

export interface SignUpReq {
  age: number;
  gender?: number | null;
  name: string;
  password: string;
  username: string;
}
