import {
  permissionListResource,
  permissionHandleAuthAssociateLimitResource,
  gamesCenterGeneralTagsResource,
  mainGameCenterGeneralResource,
  gameCenterGeneralCompanyResource,
  gameCenterSpuManagementResource,
  gamesManagementSpuUploadRecordResource,
  gamesCenterManagementSpuNoticeResource,
  gamesCenterSkuManagementResource,
  gamesCenterManagementSkuNoticeResource,
  gamesManagementSpuCheckSkuResource,
  customUserManagementResource,
  gamesCenterCommentListResource,
  gamesCenterCommentRecycleBinResource,
  marketActivityResource,
  marketActivityGoodsModalButtonResource,
  managerManagementResource,
  managersManagementPermissionTransferResource,
  managersManagementMenuTransferResource,
  permissionRoleManagementResource,
  managerRoleAuditResource,
} from './pages/main/resources';

export const resources = [
  permissionListResource,
  permissionHandleAuthAssociateLimitResource,
  gamesCenterGeneralTagsResource,
  mainGameCenterGeneralResource,
  gameCenterGeneralCompanyResource,
  gameCenterSpuManagementResource,
  gamesManagementSpuUploadRecordResource,
  gamesCenterManagementSpuNoticeResource,
  gamesCenterSkuManagementResource,
  gamesCenterManagementSkuNoticeResource,
  gamesManagementSpuCheckSkuResource,
  customUserManagementResource,
  gamesCenterCommentListResource,
  gamesCenterCommentRecycleBinResource,
  marketActivityResource,
  marketActivityGoodsModalButtonResource,
  managerManagementResource,
  managersManagementPermissionTransferResource,
  managersManagementMenuTransferResource,
  permissionRoleManagementResource,
  managerRoleAuditResource,
];
