import {
  permissionListResource,
  permissionHandleAuthAssociateLimitResource,
  permissionsMenuRouterAssociateResource,
  gamesCenterGeneralTagsResource,
  mainGameCenterGeneralResource,
  gameCenterGeneralCompanyResource,
  gameCenterSpuManagementResource,
  gamesManagementSpuUploadRecordResource,
  gamesCenterManagementSpuNoticeResource,
  gamesCenterSkuManagementResource,
  gamesCenterManagementSkuNoticeResource,
  gamesManagementSpuCheckSkuResource,
  customUserManagementResource,
  gamesCenterCommentListResource,
  gamesCenterCommentRecycleBinResource,
  marketActivityResource,
  marketActivityGoodsModalButtonResource,
} from './pages/main/resources';

export const resources = [
  permissionListResource,
  permissionHandleAuthAssociateLimitResource,
  permissionsMenuRouterAssociateResource,
  gamesCenterGeneralTagsResource,
  mainGameCenterGeneralResource,
  gameCenterGeneralCompanyResource,
  gameCenterSpuManagementResource,
  gamesManagementSpuUploadRecordResource,
  gamesCenterManagementSpuNoticeResource,
  gamesCenterSkuManagementResource,
  gamesCenterManagementSkuNoticeResource,
  gamesManagementSpuCheckSkuResource,
  customUserManagementResource,
  gamesCenterCommentListResource,
  gamesCenterCommentRecycleBinResource,
  marketActivityResource,
  marketActivityGoodsModalButtonResource,
];
