/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  useMutation
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  AuthLimitRes,
  GetAuthLimitParams,
  AdminInfoRes,
  ResPonseString,
  LoginBody,
  PermissionLimitRes,
  GetPermissionParams,
  UpdatePermissionBody,
  DeletePermissionParams,
  ResPonseU8,
  PermissionAssociateAuthReqBody,
  DisassociateParams,
  PermissionAssociateAuthLimitRes,
  GetPermissionAuthParams,
  RoutesVecRes,
  UpdateRouteReq,
  DeleteRouterParams
} from './schema'
import { custom_instance } from './custom_instance';
import type { ErrorType } from './custom_instance';



/**
 * auth limit
 * @summary auth limit
 */
export const getAuthLimit = (
    params?: GetAuthLimitParams,
 signal?: AbortSignal
) => {
      return custom_instance<AuthLimitRes>(
      {url: `/manager/auth`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetAuthLimitQueryKey = (params?: GetAuthLimitParams,) => [`/manager/auth`, ...(params ? [params]: [])] as const;
  

    
export const getGetAuthLimitQueryOptions = <TData = Awaited<ReturnType<typeof getAuthLimit>>, TError = ErrorType<unknown>>(params?: GetAuthLimitParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthLimit>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAuthLimit>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthLimitQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthLimit>>> = ({ signal }) => getAuthLimit(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAuthLimitQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthLimit>>>
export type GetAuthLimitQueryError = ErrorType<unknown>

/**
 * @summary auth limit
 */
export const useGetAuthLimit = <TData = Awaited<ReturnType<typeof getAuthLimit>>, TError = ErrorType<unknown>>(
 params?: GetAuthLimitParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthLimit>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAuthLimitQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


export const getAdminInfo = (
    
 signal?: AbortSignal
) => {
      return custom_instance<AdminInfoRes>(
      {url: `/manager/auth/info`, method: 'get', signal
    },
      );
    }
  

export const getGetAdminInfoQueryKey = () => [`/manager/auth/info`] as const;
  

    
export const getGetAdminInfoQueryOptions = <TData = Awaited<ReturnType<typeof getAdminInfo>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminInfo>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAdminInfo>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminInfoQueryKey();

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminInfo>>> = ({ signal }) => getAdminInfo(signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAdminInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminInfo>>>
export type GetAdminInfoQueryError = ErrorType<unknown>

export const useGetAdminInfo = <TData = Awaited<ReturnType<typeof getAdminInfo>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminInfo>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAdminInfoQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * sign in
 * @summary sign in
 */
export const signIn = (
    loginBody: LoginBody,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/auth/signIn`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: loginBody
    },
      );
    }
  


export const getSignInMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: LoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: LoginBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signIn>>, {data: LoginBody}> = (props) => {
          const {data} = props ?? {};

          return  signIn(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type SignInMutationResult = NonNullable<Awaited<ReturnType<typeof signIn>>>
    export type SignInMutationBody = LoginBody
    export type SignInMutationError = ErrorType<unknown>

    /**
 * @summary sign in
 */
export const useSignIn = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: LoginBody}, TContext>, }
) => {
    
      const mutationOptions = getSignInMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * permission limit
 * @summary permission limit
 */
export const getPermission = (
    params?: GetPermissionParams,
 signal?: AbortSignal
) => {
      return custom_instance<PermissionLimitRes>(
      {url: `/manager/permission`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetPermissionQueryKey = (params?: GetPermissionParams,) => [`/manager/permission`, ...(params ? [params]: [])] as const;
  

    
export const getGetPermissionQueryOptions = <TData = Awaited<ReturnType<typeof getPermission>>, TError = ErrorType<unknown>>(params?: GetPermissionParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermission>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getPermission>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPermissionQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPermission>>> = ({ signal }) => getPermission(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetPermissionQueryResult = NonNullable<Awaited<ReturnType<typeof getPermission>>>
export type GetPermissionQueryError = ErrorType<unknown>

/**
 * @summary permission limit
 */
export const useGetPermission = <TData = Awaited<ReturnType<typeof getPermission>>, TError = ErrorType<unknown>>(
 params?: GetPermissionParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermission>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPermissionQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * permission update
 * @summary permission update
 */
export const updatePermission = (
    updatePermissionBody: UpdatePermissionBody,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/permission`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: updatePermissionBody
    },
      );
    }
  


export const getUpdatePermissionMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{data: UpdatePermissionBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{data: UpdatePermissionBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePermission>>, {data: UpdatePermissionBody}> = (props) => {
          const {data} = props ?? {};

          return  updatePermission(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type UpdatePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof updatePermission>>>
    export type UpdatePermissionMutationBody = UpdatePermissionBody
    export type UpdatePermissionMutationError = ErrorType<unknown>

    /**
 * @summary permission update
 */
export const useUpdatePermission = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{data: UpdatePermissionBody}, TContext>, }
) => {
    
      const mutationOptions = getUpdatePermissionMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * permission delete
 * @summary permission delete
 */
export const deletePermission = (
    params: DeletePermissionParams,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/permission`, method: 'delete',
        params
    },
      );
    }
  


export const getDeletePermissionMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermission>>, TError,{params: DeletePermissionParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePermission>>, TError,{params: DeletePermissionParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePermission>>, {params: DeletePermissionParams}> = (props) => {
          const {params} = props ?? {};

          return  deletePermission(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DeletePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof deletePermission>>>
    
    export type DeletePermissionMutationError = ErrorType<unknown>

    /**
 * @summary permission delete
 */
export const useDeletePermission = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermission>>, TError,{params: DeletePermissionParams}, TContext>, }
) => {
    
      const mutationOptions = getDeletePermissionMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * associate permission to auth
 * @summary associate permission to auth
 */
export const associate = (
    permissionAssociateAuthReqBody: PermissionAssociateAuthReqBody,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/permission/associate`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: permissionAssociateAuthReqBody
    },
      );
    }
  


export const getAssociateMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associate>>, TError,{data: PermissionAssociateAuthReqBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof associate>>, TError,{data: PermissionAssociateAuthReqBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof associate>>, {data: PermissionAssociateAuthReqBody}> = (props) => {
          const {data} = props ?? {};

          return  associate(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type AssociateMutationResult = NonNullable<Awaited<ReturnType<typeof associate>>>
    export type AssociateMutationBody = PermissionAssociateAuthReqBody
    export type AssociateMutationError = ErrorType<unknown>

    /**
 * @summary associate permission to auth
 */
export const useAssociate = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associate>>, TError,{data: PermissionAssociateAuthReqBody}, TContext>, }
) => {
    
      const mutationOptions = getAssociateMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * associate permission to auth
 * @summary associate permission to auth
 */
export const disassociate = (
    params: DisassociateParams,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/permission/associate`, method: 'delete',
        params
    },
      );
    }
  


export const getDisassociateMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disassociate>>, TError,{params: DisassociateParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof disassociate>>, TError,{params: DisassociateParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disassociate>>, {params: DisassociateParams}> = (props) => {
          const {params} = props ?? {};

          return  disassociate(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DisassociateMutationResult = NonNullable<Awaited<ReturnType<typeof disassociate>>>
    
    export type DisassociateMutationError = ErrorType<unknown>

    /**
 * @summary associate permission to auth
 */
export const useDisassociate = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disassociate>>, TError,{params: DisassociateParams}, TContext>, }
) => {
    
      const mutationOptions = getDisassociateMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * get permission auth with whether is associated
 * @summary get permission auth with whether is associated
 */
export const getPermissionAuth = (
    params: GetPermissionAuthParams,
 signal?: AbortSignal
) => {
      return custom_instance<PermissionAssociateAuthLimitRes>(
      {url: `/manager/permission/associate/auth`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetPermissionAuthQueryKey = (params: GetPermissionAuthParams,) => [`/manager/permission/associate/auth`, ...(params ? [params]: [])] as const;
  

    
export const getGetPermissionAuthQueryOptions = <TData = Awaited<ReturnType<typeof getPermissionAuth>>, TError = ErrorType<unknown>>(params: GetPermissionAuthParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermissionAuth>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getPermissionAuth>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPermissionAuthQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPermissionAuth>>> = ({ signal }) => getPermissionAuth(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetPermissionAuthQueryResult = NonNullable<Awaited<ReturnType<typeof getPermissionAuth>>>
export type GetPermissionAuthQueryError = ErrorType<unknown>

/**
 * @summary get permission auth with whether is associated
 */
export const useGetPermissionAuth = <TData = Awaited<ReturnType<typeof getPermissionAuth>>, TError = ErrorType<unknown>>(
 params: GetPermissionAuthParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermissionAuth>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPermissionAuthQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * get routes array
 * @summary get routes array
 */
export const getRouter = (
    
 signal?: AbortSignal
) => {
      return custom_instance<RoutesVecRes>(
      {url: `/manager/router`, method: 'get', signal
    },
      );
    }
  

export const getGetRouterQueryKey = () => [`/manager/router`] as const;
  

    
export const getGetRouterQueryOptions = <TData = Awaited<ReturnType<typeof getRouter>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRouter>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getRouter>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRouterQueryKey();

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRouter>>> = ({ signal }) => getRouter(signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetRouterQueryResult = NonNullable<Awaited<ReturnType<typeof getRouter>>>
export type GetRouterQueryError = ErrorType<unknown>

/**
 * @summary get routes array
 */
export const useGetRouter = <TData = Awaited<ReturnType<typeof getRouter>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRouter>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRouterQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * update router
 * @summary update router
 */
export const updateRouter = (
    updateRouteReq: UpdateRouteReq,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/router`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: updateRouteReq
    },
      );
    }
  


export const getUpdateRouterMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRouter>>, TError,{data: UpdateRouteReq}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRouter>>, TError,{data: UpdateRouteReq}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRouter>>, {data: UpdateRouteReq}> = (props) => {
          const {data} = props ?? {};

          return  updateRouter(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type UpdateRouterMutationResult = NonNullable<Awaited<ReturnType<typeof updateRouter>>>
    export type UpdateRouterMutationBody = UpdateRouteReq
    export type UpdateRouterMutationError = ErrorType<unknown>

    /**
 * @summary update router
 */
export const useUpdateRouter = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRouter>>, TError,{data: UpdateRouteReq}, TContext>, }
) => {
    
      const mutationOptions = getUpdateRouterMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * delete router
 * @summary delete router
 */
export const deleteRouter = (
    params: DeleteRouterParams,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/router`, method: 'delete',
        params
    },
      );
    }
  


export const getDeleteRouterMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRouter>>, TError,{params: DeleteRouterParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteRouter>>, TError,{params: DeleteRouterParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRouter>>, {params: DeleteRouterParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteRouter(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DeleteRouterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRouter>>>
    
    export type DeleteRouterMutationError = ErrorType<unknown>

    /**
 * @summary delete router
 */
export const useDeleteRouter = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRouter>>, TError,{params: DeleteRouterParams}, TContext>, }
) => {
    
      const mutationOptions = getDeleteRouterMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * get all menu
 * @summary get all menu
 */
export const getAllRouter = (
    
 signal?: AbortSignal
) => {
      return custom_instance<RoutesVecRes>(
      {url: `/manager/router/all`, method: 'get', signal
    },
      );
    }
  

export const getGetAllRouterQueryKey = () => [`/manager/router/all`] as const;
  

    
export const getGetAllRouterQueryOptions = <TData = Awaited<ReturnType<typeof getAllRouter>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllRouter>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAllRouter>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllRouterQueryKey();

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRouter>>> = ({ signal }) => getAllRouter(signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAllRouterQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRouter>>>
export type GetAllRouterQueryError = ErrorType<unknown>

/**
 * @summary get all menu
 */
export const useGetAllRouter = <TData = Awaited<ReturnType<typeof getAllRouter>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllRouter>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllRouterQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


