/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * actic_web_app_project
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  useMutation
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  AuthLimitRes,
  GetAuthLimitParams,
  AdminInfoRes,
  ResPonseString,
  LoginBody,
  GameTagsRes,
  GetTagsLimitParams,
  ResPonseU8,
  UpdateTagReq,
  DeleteTagsParams,
  GameTypeRes,
  GetGameTypesParams,
  UpdateGameTypeReq,
  DeleteGameTypeParams,
  PermissionLimitRes,
  GetPermissionParams,
  UpdatePermissionBody,
  DeletePermissionParams,
  PermissionAssociateAuthReqBody,
  DisassociateParams,
  PermissionAssociateAuthLimitRes,
  GetPermissionAuthParams,
  RoutesVecRes,
  UpdateRouteReq,
  DeleteRouterParams,
  AssociateRouterAuthReq,
  RouterAssociateAuthLimitRes,
  GetAuthWithRouterParams,
  AccessKeyRes
} from './schema'
import { custom_instance } from './custom_instance';
import type { ErrorType } from './custom_instance';



/**
 * auth limit
 * @summary auth limit
 */
export const getAuthLimit = (
    params?: GetAuthLimitParams,
 signal?: AbortSignal
) => {
      return custom_instance<AuthLimitRes>(
      {url: `/manager/auth`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetAuthLimitQueryKey = (params?: GetAuthLimitParams,) => [`/manager/auth`, ...(params ? [params]: [])] as const;
  

    
export const getGetAuthLimitQueryOptions = <TData = Awaited<ReturnType<typeof getAuthLimit>>, TError = ErrorType<unknown>>(params?: GetAuthLimitParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthLimit>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAuthLimit>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthLimitQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthLimit>>> = ({ signal }) => getAuthLimit(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAuthLimitQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthLimit>>>
export type GetAuthLimitQueryError = ErrorType<unknown>

/**
 * @summary auth limit
 */
export const useGetAuthLimit = <TData = Awaited<ReturnType<typeof getAuthLimit>>, TError = ErrorType<unknown>>(
 params?: GetAuthLimitParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthLimit>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAuthLimitQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


export const getAdminInfo = (
    
 signal?: AbortSignal
) => {
      return custom_instance<AdminInfoRes>(
      {url: `/manager/auth/info`, method: 'get', signal
    },
      );
    }
  

export const getGetAdminInfoQueryKey = () => [`/manager/auth/info`] as const;
  

    
export const getGetAdminInfoQueryOptions = <TData = Awaited<ReturnType<typeof getAdminInfo>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminInfo>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAdminInfo>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminInfoQueryKey();

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminInfo>>> = ({ signal }) => getAdminInfo(signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAdminInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminInfo>>>
export type GetAdminInfoQueryError = ErrorType<unknown>

export const useGetAdminInfo = <TData = Awaited<ReturnType<typeof getAdminInfo>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminInfo>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAdminInfoQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * sign in
 * @summary sign in
 */
export const signIn = (
    loginBody: LoginBody,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/auth/signIn`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: loginBody
    },
      );
    }
  


export const getSignInMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: LoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: LoginBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signIn>>, {data: LoginBody}> = (props) => {
          const {data} = props ?? {};

          return  signIn(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type SignInMutationResult = NonNullable<Awaited<ReturnType<typeof signIn>>>
    export type SignInMutationBody = LoginBody
    export type SignInMutationError = ErrorType<unknown>

    /**
 * @summary sign in
 */
export const useSignIn = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError,{data: LoginBody}, TContext>, }
) => {
    
      const mutationOptions = getSignInMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * get tags limit
 * @summary get tags limit
 */
export const getTagsLimit = (
    params?: GetTagsLimitParams,
 signal?: AbortSignal
) => {
      return custom_instance<GameTagsRes>(
      {url: `/manager/gamesCenter/general/tags`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetTagsLimitQueryKey = (params?: GetTagsLimitParams,) => [`/manager/gamesCenter/general/tags`, ...(params ? [params]: [])] as const;
  

    
export const getGetTagsLimitQueryOptions = <TData = Awaited<ReturnType<typeof getTagsLimit>>, TError = ErrorType<unknown>>(params?: GetTagsLimitParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTagsLimit>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getTagsLimit>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTagsLimitQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTagsLimit>>> = ({ signal }) => getTagsLimit(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetTagsLimitQueryResult = NonNullable<Awaited<ReturnType<typeof getTagsLimit>>>
export type GetTagsLimitQueryError = ErrorType<unknown>

/**
 * @summary get tags limit
 */
export const useGetTagsLimit = <TData = Awaited<ReturnType<typeof getTagsLimit>>, TError = ErrorType<unknown>>(
 params?: GetTagsLimitParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTagsLimit>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetTagsLimitQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * update tags
 * @summary update tags
 */
export const updateTags = (
    updateTagReq: UpdateTagReq,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/gamesCenter/general/tags`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: updateTagReq
    },
      );
    }
  


export const getUpdateTagsMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTags>>, TError,{data: UpdateTagReq}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTags>>, TError,{data: UpdateTagReq}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTags>>, {data: UpdateTagReq}> = (props) => {
          const {data} = props ?? {};

          return  updateTags(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type UpdateTagsMutationResult = NonNullable<Awaited<ReturnType<typeof updateTags>>>
    export type UpdateTagsMutationBody = UpdateTagReq
    export type UpdateTagsMutationError = ErrorType<unknown>

    /**
 * @summary update tags
 */
export const useUpdateTags = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTags>>, TError,{data: UpdateTagReq}, TContext>, }
) => {
    
      const mutationOptions = getUpdateTagsMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * delete tags
 * @summary delete tags
 */
export const deleteTags = (
    params: DeleteTagsParams,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/gamesCenter/general/tags`, method: 'delete',
        params
    },
      );
    }
  


export const getDeleteTagsMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTags>>, TError,{params: DeleteTagsParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTags>>, TError,{params: DeleteTagsParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTags>>, {params: DeleteTagsParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteTags(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DeleteTagsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTags>>>
    
    export type DeleteTagsMutationError = ErrorType<unknown>

    /**
 * @summary delete tags
 */
export const useDeleteTags = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTags>>, TError,{params: DeleteTagsParams}, TContext>, }
) => {
    
      const mutationOptions = getDeleteTagsMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * get game types limit
 * @summary get game types limit
 */
export const getGameTypes = (
    params?: GetGameTypesParams,
 signal?: AbortSignal
) => {
      return custom_instance<GameTypeRes>(
      {url: `/manager/gamesCenter/general/types`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetGameTypesQueryKey = (params?: GetGameTypesParams,) => [`/manager/gamesCenter/general/types`, ...(params ? [params]: [])] as const;
  

    
export const getGetGameTypesQueryOptions = <TData = Awaited<ReturnType<typeof getGameTypes>>, TError = ErrorType<unknown>>(params?: GetGameTypesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGameTypes>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getGameTypes>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameTypesQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameTypes>>> = ({ signal }) => getGameTypes(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetGameTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getGameTypes>>>
export type GetGameTypesQueryError = ErrorType<unknown>

/**
 * @summary get game types limit
 */
export const useGetGameTypes = <TData = Awaited<ReturnType<typeof getGameTypes>>, TError = ErrorType<unknown>>(
 params?: GetGameTypesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGameTypes>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetGameTypesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * update game types
 * @summary update game types
 */
export const updateGameType = (
    updateGameTypeReq: UpdateGameTypeReq,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/gamesCenter/general/types`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: updateGameTypeReq
    },
      );
    }
  


export const getUpdateGameTypeMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGameType>>, TError,{data: UpdateGameTypeReq}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateGameType>>, TError,{data: UpdateGameTypeReq}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGameType>>, {data: UpdateGameTypeReq}> = (props) => {
          const {data} = props ?? {};

          return  updateGameType(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type UpdateGameTypeMutationResult = NonNullable<Awaited<ReturnType<typeof updateGameType>>>
    export type UpdateGameTypeMutationBody = UpdateGameTypeReq
    export type UpdateGameTypeMutationError = ErrorType<unknown>

    /**
 * @summary update game types
 */
export const useUpdateGameType = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGameType>>, TError,{data: UpdateGameTypeReq}, TContext>, }
) => {
    
      const mutationOptions = getUpdateGameTypeMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * delete game type
 * @summary delete game type
 */
export const deleteGameType = (
    params: DeleteGameTypeParams,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/gamesCenter/general/types`, method: 'delete',
        params
    },
      );
    }
  


export const getDeleteGameTypeMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGameType>>, TError,{params: DeleteGameTypeParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteGameType>>, TError,{params: DeleteGameTypeParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGameType>>, {params: DeleteGameTypeParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteGameType(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DeleteGameTypeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGameType>>>
    
    export type DeleteGameTypeMutationError = ErrorType<unknown>

    /**
 * @summary delete game type
 */
export const useDeleteGameType = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGameType>>, TError,{params: DeleteGameTypeParams}, TContext>, }
) => {
    
      const mutationOptions = getDeleteGameTypeMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * permission limit
 * @summary permission limit
 */
export const getPermission = (
    params?: GetPermissionParams,
 signal?: AbortSignal
) => {
      return custom_instance<PermissionLimitRes>(
      {url: `/manager/permission`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetPermissionQueryKey = (params?: GetPermissionParams,) => [`/manager/permission`, ...(params ? [params]: [])] as const;
  

    
export const getGetPermissionQueryOptions = <TData = Awaited<ReturnType<typeof getPermission>>, TError = ErrorType<unknown>>(params?: GetPermissionParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermission>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getPermission>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPermissionQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPermission>>> = ({ signal }) => getPermission(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetPermissionQueryResult = NonNullable<Awaited<ReturnType<typeof getPermission>>>
export type GetPermissionQueryError = ErrorType<unknown>

/**
 * @summary permission limit
 */
export const useGetPermission = <TData = Awaited<ReturnType<typeof getPermission>>, TError = ErrorType<unknown>>(
 params?: GetPermissionParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermission>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPermissionQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * permission update
 * @summary permission update
 */
export const updatePermission = (
    updatePermissionBody: UpdatePermissionBody,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/permission`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: updatePermissionBody
    },
      );
    }
  


export const getUpdatePermissionMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{data: UpdatePermissionBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{data: UpdatePermissionBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePermission>>, {data: UpdatePermissionBody}> = (props) => {
          const {data} = props ?? {};

          return  updatePermission(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type UpdatePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof updatePermission>>>
    export type UpdatePermissionMutationBody = UpdatePermissionBody
    export type UpdatePermissionMutationError = ErrorType<unknown>

    /**
 * @summary permission update
 */
export const useUpdatePermission = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePermission>>, TError,{data: UpdatePermissionBody}, TContext>, }
) => {
    
      const mutationOptions = getUpdatePermissionMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * permission delete
 * @summary permission delete
 */
export const deletePermission = (
    params: DeletePermissionParams,
 ) => {
      return custom_instance<ResPonseString>(
      {url: `/manager/permission`, method: 'delete',
        params
    },
      );
    }
  


export const getDeletePermissionMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermission>>, TError,{params: DeletePermissionParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePermission>>, TError,{params: DeletePermissionParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePermission>>, {params: DeletePermissionParams}> = (props) => {
          const {params} = props ?? {};

          return  deletePermission(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DeletePermissionMutationResult = NonNullable<Awaited<ReturnType<typeof deletePermission>>>
    
    export type DeletePermissionMutationError = ErrorType<unknown>

    /**
 * @summary permission delete
 */
export const useDeletePermission = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePermission>>, TError,{params: DeletePermissionParams}, TContext>, }
) => {
    
      const mutationOptions = getDeletePermissionMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * associate permission to auth
 * @summary associate permission to auth
 */
export const associate = (
    permissionAssociateAuthReqBody: PermissionAssociateAuthReqBody,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/permission/associate`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: permissionAssociateAuthReqBody
    },
      );
    }
  


export const getAssociateMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associate>>, TError,{data: PermissionAssociateAuthReqBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof associate>>, TError,{data: PermissionAssociateAuthReqBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof associate>>, {data: PermissionAssociateAuthReqBody}> = (props) => {
          const {data} = props ?? {};

          return  associate(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type AssociateMutationResult = NonNullable<Awaited<ReturnType<typeof associate>>>
    export type AssociateMutationBody = PermissionAssociateAuthReqBody
    export type AssociateMutationError = ErrorType<unknown>

    /**
 * @summary associate permission to auth
 */
export const useAssociate = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associate>>, TError,{data: PermissionAssociateAuthReqBody}, TContext>, }
) => {
    
      const mutationOptions = getAssociateMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * associate permission to auth
 * @summary associate permission to auth
 */
export const disassociate = (
    params: DisassociateParams,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/permission/associate`, method: 'delete',
        params
    },
      );
    }
  


export const getDisassociateMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disassociate>>, TError,{params: DisassociateParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof disassociate>>, TError,{params: DisassociateParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disassociate>>, {params: DisassociateParams}> = (props) => {
          const {params} = props ?? {};

          return  disassociate(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DisassociateMutationResult = NonNullable<Awaited<ReturnType<typeof disassociate>>>
    
    export type DisassociateMutationError = ErrorType<unknown>

    /**
 * @summary associate permission to auth
 */
export const useDisassociate = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disassociate>>, TError,{params: DisassociateParams}, TContext>, }
) => {
    
      const mutationOptions = getDisassociateMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * get permission auth with whether is associated
 * @summary get permission auth with whether is associated
 */
export const getPermissionAuth = (
    params: GetPermissionAuthParams,
 signal?: AbortSignal
) => {
      return custom_instance<PermissionAssociateAuthLimitRes>(
      {url: `/manager/permission/associate/auth`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetPermissionAuthQueryKey = (params: GetPermissionAuthParams,) => [`/manager/permission/associate/auth`, ...(params ? [params]: [])] as const;
  

    
export const getGetPermissionAuthQueryOptions = <TData = Awaited<ReturnType<typeof getPermissionAuth>>, TError = ErrorType<unknown>>(params: GetPermissionAuthParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermissionAuth>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getPermissionAuth>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPermissionAuthQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPermissionAuth>>> = ({ signal }) => getPermissionAuth(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetPermissionAuthQueryResult = NonNullable<Awaited<ReturnType<typeof getPermissionAuth>>>
export type GetPermissionAuthQueryError = ErrorType<unknown>

/**
 * @summary get permission auth with whether is associated
 */
export const useGetPermissionAuth = <TData = Awaited<ReturnType<typeof getPermissionAuth>>, TError = ErrorType<unknown>>(
 params: GetPermissionAuthParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPermissionAuth>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPermissionAuthQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * get routes array
 * @summary get routes array
 */
export const getRouter = (
    
 signal?: AbortSignal
) => {
      return custom_instance<RoutesVecRes>(
      {url: `/manager/router`, method: 'get', signal
    },
      );
    }
  

export const getGetRouterQueryKey = () => [`/manager/router`] as const;
  

    
export const getGetRouterQueryOptions = <TData = Awaited<ReturnType<typeof getRouter>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRouter>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getRouter>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRouterQueryKey();

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRouter>>> = ({ signal }) => getRouter(signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetRouterQueryResult = NonNullable<Awaited<ReturnType<typeof getRouter>>>
export type GetRouterQueryError = ErrorType<unknown>

/**
 * @summary get routes array
 */
export const useGetRouter = <TData = Awaited<ReturnType<typeof getRouter>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRouter>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetRouterQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * update router
 * @summary update router
 */
export const updateRouter = (
    updateRouteReq: UpdateRouteReq,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/router`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: updateRouteReq
    },
      );
    }
  


export const getUpdateRouterMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRouter>>, TError,{data: UpdateRouteReq}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRouter>>, TError,{data: UpdateRouteReq}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRouter>>, {data: UpdateRouteReq}> = (props) => {
          const {data} = props ?? {};

          return  updateRouter(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type UpdateRouterMutationResult = NonNullable<Awaited<ReturnType<typeof updateRouter>>>
    export type UpdateRouterMutationBody = UpdateRouteReq
    export type UpdateRouterMutationError = ErrorType<unknown>

    /**
 * @summary update router
 */
export const useUpdateRouter = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRouter>>, TError,{data: UpdateRouteReq}, TContext>, }
) => {
    
      const mutationOptions = getUpdateRouterMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * delete router
 * @summary delete router
 */
export const deleteRouter = (
    params: DeleteRouterParams,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/router`, method: 'delete',
        params
    },
      );
    }
  


export const getDeleteRouterMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRouter>>, TError,{params: DeleteRouterParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteRouter>>, TError,{params: DeleteRouterParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRouter>>, {params: DeleteRouterParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteRouter(params,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type DeleteRouterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRouter>>>
    
    export type DeleteRouterMutationError = ErrorType<unknown>

    /**
 * @summary delete router
 */
export const useDeleteRouter = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRouter>>, TError,{params: DeleteRouterParams}, TContext>, }
) => {
    
      const mutationOptions = getDeleteRouterMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * get all menu
 * @summary get all menu
 */
export const getAllRouter = (
    
 signal?: AbortSignal
) => {
      return custom_instance<RoutesVecRes>(
      {url: `/manager/router/all`, method: 'get', signal
    },
      );
    }
  

export const getGetAllRouterQueryKey = () => [`/manager/router/all`] as const;
  

    
export const getGetAllRouterQueryOptions = <TData = Awaited<ReturnType<typeof getAllRouter>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllRouter>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAllRouter>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllRouterQueryKey();

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRouter>>> = ({ signal }) => getAllRouter(signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAllRouterQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRouter>>>
export type GetAllRouterQueryError = ErrorType<unknown>

/**
 * @summary get all menu
 */
export const useGetAllRouter = <TData = Awaited<ReturnType<typeof getAllRouter>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllRouter>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAllRouterQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


export const associateAuthRouter = (
    associateRouterAuthReq: AssociateRouterAuthReq,
 ) => {
      return custom_instance<ResPonseU8>(
      {url: `/manager/router/associate`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: associateRouterAuthReq
    },
      );
    }
  


export const getAssociateAuthRouterMutationOptions = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associateAuthRouter>>, TError,{data: AssociateRouterAuthReq}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof associateAuthRouter>>, TError,{data: AssociateRouterAuthReq}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof associateAuthRouter>>, {data: AssociateRouterAuthReq}> = (props) => {
          const {data} = props ?? {};

          return  associateAuthRouter(data,)
        }

        

 
   return  { mutationFn, ...mutationOptions }}

    export type AssociateAuthRouterMutationResult = NonNullable<Awaited<ReturnType<typeof associateAuthRouter>>>
    export type AssociateAuthRouterMutationBody = AssociateRouterAuthReq
    export type AssociateAuthRouterMutationError = ErrorType<unknown>

    export const useAssociateAuthRouter = <TError = ErrorType<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associateAuthRouter>>, TError,{data: AssociateRouterAuthReq}, TContext>, }
) => {
    
      const mutationOptions = getAssociateAuthRouterMutationOptions(options);
     
      return useMutation(mutationOptions);
    }
    
/**
 * get auth limit with router associated
 * @summary get auth limit with router associated
 */
export const getAuthWithRouter = (
    params: GetAuthWithRouterParams,
 signal?: AbortSignal
) => {
      return custom_instance<RouterAssociateAuthLimitRes>(
      {url: `/manager/router/associate/auth`, method: 'get',
        params, signal
    },
      );
    }
  

export const getGetAuthWithRouterQueryKey = (params: GetAuthWithRouterParams,) => [`/manager/router/associate/auth`, ...(params ? [params]: [])] as const;
  

    
export const getGetAuthWithRouterQueryOptions = <TData = Awaited<ReturnType<typeof getAuthWithRouter>>, TError = ErrorType<unknown>>(params: GetAuthWithRouterParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthWithRouter>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAuthWithRouter>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthWithRouterQueryKey(params);

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthWithRouter>>> = ({ signal }) => getAuthWithRouter(params, signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAuthWithRouterQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthWithRouter>>>
export type GetAuthWithRouterQueryError = ErrorType<unknown>

/**
 * @summary get auth limit with router associated
 */
export const useGetAuthWithRouter = <TData = Awaited<ReturnType<typeof getAuthWithRouter>>, TError = ErrorType<unknown>>(
 params: GetAuthWithRouterParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthWithRouter>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAuthWithRouterQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


/**
 * get accessKey
 * @summary get accessKey
 */
export const getAccessKey = (
    
 signal?: AbortSignal
) => {
      return custom_instance<AccessKeyRes>(
      {url: `/manager/upload/accessKey`, method: 'get', signal
    },
      );
    }
  

export const getGetAccessKeyQueryKey = () => [`/manager/upload/accessKey`] as const;
  

    
export const getGetAccessKeyQueryOptions = <TData = Awaited<ReturnType<typeof getAccessKey>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAccessKey>>, TError, TData>, }
): UseQueryOptions<Awaited<ReturnType<typeof getAccessKey>>, TError, TData> & { queryKey: QueryKey } => {
const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccessKeyQueryKey();

  
  
    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccessKey>>> = ({ signal }) => getAccessKey(signal);
    
      
      
   return  { queryKey, queryFn, ...queryOptions}}

export type GetAccessKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getAccessKey>>>
export type GetAccessKeyQueryError = ErrorType<unknown>

/**
 * @summary get accessKey
 */
export const useGetAccessKey = <TData = Awaited<ReturnType<typeof getAccessKey>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAccessKey>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetAccessKeyQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


